dg/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

import coco.urls
import data_upload.urls
import dimagi.urls
import feeds.urls
import raw_data_analytics.urls

import social_website.api_urls
import social_website.urls
import videokheti.urls

from django.contrib import admin
admin.autodiscover()

from coco.data_log import send_updated_log
from coco_admin import coco_admin
from farmerbook import farmer_book_views
from output.views import video_analytics
from static_site_views import spring_analytics
from website_admin import website_admin
from mcoco_admin import mcoco_admin
import website_archive_urls
import deoanalytics.urls

coco_admin.index_template = 'social_website/index.html'
coco_admin.login_template = 'social_website/login.html'
coco_admin.logout_template = 'social_website/home.html'
website_admin.index_template = 'social_website/index.html'
website_admin.login_template = 'social_website/login.html'
website_admin.logout_template = 'social_website/home.html'
mcoco_admin.index_template = 'social_website/index.html'
mcoco_admin.login_template = 'social_website/login.html'
mcoco_admin.logout_template = 'social_website/home.html'

urlpatterns = patterns('',
    (r'^', include(social_website.urls)),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login/$', 'social_website.views.login_view', {'template_name': 'social_website/login.html'}, name='signin'),
    url(r'^signup/$', 'social_website.views.signup_view', {'template_name': 'social_website/signup.html'}, name='signup'),
    url(r'^denied/$', 'django.views.defaults.permission_denied', {'template_name': 'social_website/403.html'}),
    url(r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'social_website/password_change.html', 'post_change_redirect':'/',}, name='change_password'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    (r'^social/', include(social_website.api_urls)),
    (r'^bmgf/', include(feeds.urls)),
    (r'^archive/', include(website_archive_urls)),
    (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.STATIC_DOC_ROOT, 'show_indexes': True}),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(coco_admin.urls)),
    (r'^adminwebsite/', include(website_admin.urls)),
    (r'^mcocoadmin/', include(mcoco_admin.urls)),
    (r'^adminblog/', include(admin.site.urls)),
    (r'^data_upload/', include(data_upload.urls)),
    (r'^coco/', include(coco.urls)),
    (r'^dimagi/', include(dimagi.urls)),
    (r'^analytics/', include('output.urls')),
    (r'^video/?$',video_analytics.video),
    (r'^raw_data_analytics/', include(raw_data_analytics.urls)),

    (r'^get_log/?$', send_updated_log),
    # End imports from dashboard
    ##Special page.needs to be deleted
    (r'^spring/analytics/?$', spring_analytics),
    
    # Imports from farmerbook
    (r'^farmerbook/$', farmer_book_views.get_home_page),
    (r'^farmerbook/(?P<type>\D*)/(?P<id>\d*)/$', farmer_book_views.get_home_page),
    (r'^trial/?$', farmer_book_views.get_admin_panel),
    (r'^getvillagepage/?$', farmer_book_views.get_village_page),
    (r'^getserviceproviderpage/?$', farmer_book_views.get_csp_page),
    (r'^getpartnerpage/?$', farmer_book_views.get_partner_page),
    (r'^getpersonpage/?$', farmer_book_views.get_person_page),
    (r'^getgrouppage/?$', farmer_book_views.get_group_page),
    (r'^getvillages/?$', farmer_book_views.get_villages_with_images),
    (r'^getvideosproduced/?$', farmer_book_views.get_videos_produced),
    (r'^fbconnect/', include('fbconnect.urls')),
    (r'^analytics/cocouser/',include('deoanalytics.urls')),
    (r'^analytics/vrptool/',include('vrppayment.urls')),
    (r'^coco/docs/', TemplateView.as_view(template_name='cocodoc.html')),
    (r'^agri/', include(videokheti.urls)),
    (r"^", include("mezzanine.urls")),

)

# Static files serving locally
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

people/models.py
from django.db import models
from django.db.models.signals import pre_delete, post_save

from coco.data_log import delete_log, save_log
from coco.base_models import CocoModel, DAY_CHOICES, GENDER_CHOICES
from farmerbook.managers import FarmerbookManager
from geographies.models import District, Village
from programs.models import Partner

class Animator(CocoModel):
    id = models.AutoField(primary_key = True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone_no = models.CharField(max_length=100, blank=True)
    partner = models.ForeignKey(Partner)
    district = models.ForeignKey(District, null=True, blank=True)
    assigned_villages = models.ManyToManyField(Village, related_name='assigned_villages', through='AnimatorAssignedVillage', null=True, blank=True)
    total_adoptions = models.PositiveIntegerField(default=0, blank=True, editable=False) 

    class Meta:
        unique_together = ("name", "gender", "partner", "district")

    def get_village(self):
        return None

    def get_partner(self):
        return self.partner.id

    def __unicode__(self):
        return  u'%s (%s)' % (self.name, self.district)

post_save.connect(save_log, sender=Animator)
pre_delete.connect(delete_log, sender=Animator)


class AnimatorAssignedVillage(CocoModel):
    id = models.AutoField(primary_key=True)
    animator = models.ForeignKey(Animator)
    village = models.ForeignKey(Village)
    start_date = models.DateField(null=True, blank=True)

class PersonGroup(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    group_name = models.CharField(max_length=100)
    village = models.ForeignKey(Village)
    partner = models.ForeignKey(Partner)

    class Meta:
        verbose_name = "Person group"
        unique_together = ("group_name", "village")

    def __unicode__(self):
        return  u'%s (%s)' % (self.group_name, self.village)
post_save.connect(save_log, sender=PersonGroup)
pre_delete.connect(delete_log, sender=PersonGroup)

class Person(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    person_name = models.CharField(max_length=100)
    father_name = models.CharField(max_length=100, blank=True)
    age = models.IntegerField(max_length=3, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone_no = models.CharField(max_length=100, blank=True)
    village = models.ForeignKey(Village)
    group = models.ForeignKey(PersonGroup, null=True, blank=True)
    date_of_joining = models.DateField(null=True, blank=True)
    image_exists = models.BooleanField(default=False)
    partner = models.ForeignKey(Partner)
    objects = models.Manager() #The default manager
    farmerbook_objects = FarmerbookManager() #The manager for farmerbook

    class Meta:
        unique_together = ("person_name", "father_name", "village")

    def __unicode__(self):
        display = "%s" % (self.person_name)
        display += " (%s)" % self.father_name if self.father_name.strip()!="" else "" 
        display += " (%s)" % self.group.group_name if self.group is not None else ""
        display += " (%s)" % self.village.village_name
        return  display
post_save.connect(save_log, sender=Person)
pre_delete.connect(delete_log, sender=Person)

videos/models.py
from django.db import models
from django.db.models.signals import pre_delete, post_save

from coco.data_log import delete_log, save_log
from coco.base_models import ACTORS, CocoModel, STORYBASE, SUITABLE_FOR, VIDEO_TYPE
from geographies.models import Village
from programs.models import Partner
from people.models import Animator, Person

class PracticeSector(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    name = models.CharField(max_length=500)

    def __unicode__(self):
        return self.name


class PracticeSubSector(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    name = models.CharField(max_length=500)

    def __unicode__(self):
        return self.name


class PracticeTopic(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    name = models.CharField(max_length=500)

    def __unicode__(self):
        return self.name


class PracticeSubtopic(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    name = models.CharField(max_length=500)

    def __unicode__(self):
        return self.name


class PracticeSubject(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    name = models.CharField(max_length=500)

    def __unicode__(self):
        return self.name


class Practice(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    practice_name = models.CharField(null=True, blank=True, max_length=200)
    practice_sector = models.ForeignKey(PracticeSector, default=1) 
    practice_subsector = models.ForeignKey(PracticeSubSector, null=True, blank=True)
    practice_topic = models.ForeignKey(PracticeTopic, null=True, blank=True)
    practice_subtopic = models.ForeignKey(PracticeSubtopic, null=True, blank=True)
    practice_subject = models.ForeignKey(PracticeSubject, null=True, blank=True)    

    class Meta:
        verbose_name = "Practice"
        unique_together = ("practice_sector", "practice_subsector", "practice_topic", "practice_subtopic", "practice_subject")

    def __unicode__(self):
        practice_sector = '' if self.practice_sector is None else self.practice_sector.name
        practice_subject = '' if self.practice_subject is None else self.practice_subject.name
        practice_subsector = '' if self.practice_subsector is None else self.practice_subsector.name
        practice_topic = '' if self.practice_topic is None else self.practice_topic.name
        practice_subtopic = '' if self.practice_subtopic is None else self.practice_subtopic.name
        return "%s, %s, %s, %s, %s" % (practice_sector, practice_subject, practice_subsector, practice_topic, practice_subtopic)


class Language(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    language_name = models.CharField(max_length=100, unique='True')

    def get_village(self):
        return None

    def get_partner(self):
        return None
    
    def __unicode__(self):
        return self.language_name
post_save.connect(save_log, sender=Language)
pre_delete.connect(delete_log, sender=Language)


class Video(CocoModel):
    id = models.AutoField(primary_key=True)
    old_coco_id = models.BigIntegerField(editable=False, null=True)
    title = models.CharField(max_length=200)
    video_type = models.IntegerField(max_length=1, choices=VIDEO_TYPE)
    duration = models.TimeField(null=True, blank=True)
    language = models.ForeignKey(Language)
    summary = models.TextField(blank=True)
    video_production_start_date = models.DateField()
    video_production_end_date = models.DateField()
    village = models.ForeignKey(Village)
    facilitator = models.ForeignKey(Animator, related_name='facilitator')
    cameraoperator = models.ForeignKey(Animator, related_name='cameraoperator')
    approval_date = models.DateField(null=True, blank=True)
    video_suitable_for = models.IntegerField(choices=SUITABLE_FOR)
    related_practice = models.ForeignKey(Practice, blank=True, null=True)
    farmers_shown = models.ManyToManyField(Person)
    actors = models.CharField(max_length=1, choices=ACTORS)
    youtubeid = models.CharField(max_length=20, blank=True)
    partner = models.ForeignKey(Partner)
    
    class Meta:
        unique_together = ("title", "video_production_start_date", "video_production_end_date", "village")

    def __unicode__(self):
        return  u'%s (%s)' % (self.title, self.village)
post_save.connect(save_log, sender=Video)
pre_delete.connect(delete_log, sender=Video)

class NonNegotiable(CocoModel):
    id = models.AutoField(primary_key=True)
    video = models.ForeignKey(Video)
    non_negotiable = models.CharField(max_length=500)

    def __unicode__(self):
        return  u'%s' % self.non_negotiable
post_save.connect(save_log, sender=NonNegotiable)
pre_delete.connect(delete_log, sender=NonNegotiable)

dg/templates/add_animator.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en-us" xmlns="http://www.w3.org/1999/xhtml" lang="en-us"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">


<title>Add animator | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/media/css/base.css">
<link rel="stylesheet" type="text/css" href="/media/css/forms.css">
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/media/css/ie.css" /><![endif]-->


<script type="text/javascript" src="/media/js/a"></script>
<script type="text/javascript" src="/media/js/core.js"></script>
<script type="text/javascript" src="/media/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/media/js/getElementsBySelector.js"></script>
<script type="text/javascript" src="/media/js/actions.js"></script>
<script type="text/javascript" src="/media/js/calendar.js"></script>
<script type="text/javascript" src="/media/js/admin/DateTimeShortcuts.js"></script>

<meta name="robots" content="NONE,NOARCHIVE">
</head><body class="dashboard-animator change-form">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name">Digital Green administration</h1>

        </div>
        
        <div id="user-tools">
            Welcome,
            <strong>digitalgreen</strong>.

            
                
                
                    <a href="/admin/doc/">Documentation</a> /
                
                
                
                    <a href="/admin/password_change/">
                
                Change password</a> /

                
                
                    <a href="/admin/logout/">
                
                Log out</a>
            

        </div>
        
        
    </div>
    <!-- END Header -->
    
<div class="breadcrumbs">
     <a href="/admin/">Home</a> ›
     <a href="/admin/dashboard/">Dashboard</a> › 
     <a href="/dashboard/animators/">Animators</a> › 
     Add animator
</div>

    

        

    <!-- Content -->
    <div id="content" class="colM">
        
        <h1>Add animator</h1>
        <div id="content-main">



<form enctype="multipart/form-data" action="" method="post" id="animator_form">
<div>
{% if form.errors %}
    <p class="errornote">
    Please correct the errors below.
    </p>
    <ul class="errorlist"></ul>
{% endif %}




  <fieldset class="module aligned ">
  
  
{% if form.name.errors %}  
      <div class="form-row errors name  ">
      {{ form.name.errors }}
{% else %}
	<div class="form-row name">
{% endif %}
      
      <div>
          
              <label for="id_name" class="required">Name:</label>
		{{ form.name }}
          
      </div>
      
      </div>
  

{% if form.age.errors %}
      <div class="form-row errors age  ">
	{{ form.age.errors }}
{% else %}      
	<div class="form-row age">
{% endif %}
      
      <div>
          
              <label for="id_age">Age:</label>
		{{ form.age }}
          
          
      </div>
      
      </div>
  
{% if form.gender.errors %}
	<div class="form-row errors  gender">
	{{ form.gender.errors }}
{% else %}
        <div class="form-row gender  ">
{% endif %}
      
      <div>
          
              <label for="id_gender" class="required">Gender:</label>
   		{{ form.gender }}       
          
      </div>
      
      </div>
 
{% if form.csp_flag.errors %}
	<div class="form-row errors csp_flag">
	{{ form.csp_flag.errors }}
{% else %}
        <div class="form-row csp_flag  ">
{% endif %}
      
      <div>
          
              <label for="id_csp_flag">Csp flag:</label>
              {{ form.csp_flag}} 
          
      </div>
      
      </div>
  

{% if form.camera_operator_flag.errors %}
      <div class="form-row errors  camera_operator_flag  ">
	{{ form.camera_operator_flag.errors  }}
{% else %}
	<div class="form-row camera_operator_flag ">
{% endif %}
      
      
      <div>
          
              <label for="id_camera_operator_flag">Camera operator flag:</label>
         	{{ form.camera_operator_flag }} 
          
      </div>
      
      </div>
  

{% if form.facilitator_flag.errors  %}
      <div class="form-row errors facilitator_flag  ">
	{{ form.facilitator_flag.errors }}
{% else %}      
      <div class="form-row facilitator_flag ">
{% endif %}
      <div>
          
              <label for="id_facilitator_flag">Facilitator flag:</label>
		{{ form.facilitator_flag }}
</select>
          
          
      </div>
      
      </div>
 
{% if form.phone_no.errors %} 
      <div class="form-row errors phone_no  ">
	{{ form.phone_no.errors }}
{% else %}      
      <div class="form-row phone_no">
{% endif %}
      <div>
          
              <label for="id_phone_no">Phone no:</label>
              {{ form.phone_no}} 
          
      </div>
      
      </div>
  


{% if form.address.errors %}
 	<div class="form-row errors address">
	{{ form.address.errors }}
{% else %}
        <div class="form-row address  ">
{% endif %}
      
      
      <div>
          
              <label for="id_address">Address:</label>
         	{{ form.address}} 
          
      </div>
      
      </div>

{% if form.partner.errors %}  
      <div class="form-row errors partner  ">
      {{ form.partner.errors }}
{% else %}      
      <div class="form-row partner ">
{% endif %}
         <div> 
              <label for="id_partner" class="required">Partner:</label>
		{{ form.partner}}
		<a href="/dashboard/partner/add/" class="add-another" id="add_id_partner" onclick="return showAddAnotherPopup(this);"> <img src="/media/img/admin/icon_addlink.gif" alt="Add Another" height="10" width="10"></a>
          
          
      </div>
      
      </div>
 
{% if form.home_village.errors %} 
      <div class="form-row errors  home_village  ">
      {{ form.home_village.errors }}
{% else %}      
      <div class="form-row home_village">
{% endif %}
         <div> 
              <label for="id_home_village" class="required">Home village:</label>
		{{ form.home_village}}
		<a href="/admin/dashboard/village/add/" class="add-another" id="add_id_home_village" onclick="return showAddAnotherPopup(this);"> <img src="/media/img/admin/icon_addlink.gif" alt="Add Another" height="10" width="10"></a>
          
          
      </div>
      
      </div>
  
</fieldset>






    
<div class="inline-group">
  <h2>Animator Assigned Villages</h2>

<input name="animatorassignedvillage_set-TOTAL_FORMS" value="3" id="id_animatorassignedvillage_set-TOTAL_FORMS" type="hidden"><input name="animatorassignedvillage_set-INITIAL_FORMS" value="0" id="id_animatorassignedvillage_set-INITIAL_FORMS" type="hidden">

{{ formset.management_form }}
{% for form in formset.forms %}


<div class="inline-related">
  <h3><b>Animator Assigned Village:</b>&nbsp; #{{ forloop.counter }}
    
  </h3>
  
  

  
    <fieldset class="module aligned ">
  
  
	{% if form.village.errors %} 
	      <div class="form-row errors  village  ">
      		{{ form.village.errors }}
	{% else %}
	      <div class="form-row village">
        {% endif %}

      <div>
          
              <label for="id_animatorassignedvillage_set-{{ forloop.counter0 }}-village" class="required">Village:</label>
		{{ form.village }}
		<a href="/admin/dashboard/village/add/" class="add-another" id="add_id_animatorassignedvillage_set-{{ forloop.counter0 }}-village" onclick="return showAddAnotherPopup(this);"> <img src="/media/img/admin/icon_addlink.gif" alt="Add Another" height="10" width="10"></a>
          
          
      </div>
      
      </div>
  
	{% if form.start_date.errors %}
		<div class="form-row errors start_date  ">
		{{ form.start_date.errors }}
        {% else %}
      		<div class="form-row start_date">
	{% endif %}
      <div>
          
              <label for="id_animatorassignedvillage_set-{{ forloop.counter0 }}-start_date">Start date:</label>
		<input id="id_animatorassignedvillage_set-{{ forloop.counter0 }}-start_date" class="vDateField" name="animatorassignedvillage_set-{{ forloop.counter0}}-start_date" size="10" type="text"><!--span>&nbsp;<a href="javascript:DateTimeShortcuts.handleCalendarQuickLink(0,%200);">Today</a>&nbsp;|&nbsp;<a id="calendarlink0" href="javascript:DateTimeShortcuts.openCalendar(0);"><img alt="Calendar" src="add_animator_files/icon_calendar.gif"></a></span-->
          
          
      </div>
      
      </div>
  
</fieldset>

  {{ form.id }}
  {{ form.animator }}
  <!--input name="animatorassignedvillage_set-0-id" id="id_animatorassignedvillage_set-0-id" type="hidden">
  <input name="animatorassignedvillage_set-0-animator" id="id_animatorassignedvillage_set-0-animator" type="hidden"-->
</div>

{% endfor %}
<!--div class="inline-related">
  <h3><b>Animator Assigned Village:</b>&nbsp; #2
    
  </h3>
  
  

  
    <fieldset class="module aligned ">
  
  
  
      <div class="form-row village  ">
      
      
      <div>
          
              <label for="id_animatorassignedvillage_set-1-village" class="required">Village:</label><select name="animatorassignedvillage_set-1-village" id="id_animatorassignedvillage_set-1-village">
<option value="" selected="selected">---------</option>
<option value="19">village1</option>
</select><a href="http://174.129.13.106:8000/admin/dashboard/village/add/" class="add-another" id="add_id_animatorassignedvillage_set-1-village" onclick="return showAddAnotherPopup(this);"> <img src="add_animator_files/icon_addlink.gif" alt="Add Another" height="10" width="10"></a>
          
          
      </div>
      
      </div>
  
      <div class="form-row start_date  ">
      
      
      <div>
          
              <label for="id_animatorassignedvillage_set-1-start_date">Start date:</label><input id="id_animatorassignedvillage_set-1-start_date" class="vDateField" name="animatorassignedvillage_set-1-start_date" size="10" type="text"><span>&nbsp;<a href="javascript:DateTimeShortcuts.handleCalendarQuickLink(1,%200);">Today</a>&nbsp;|&nbsp;<a id="calendarlink1" href="javascript:DateTimeShortcuts.openCalendar(1);"><img alt="Calendar" src="add_animator_files/icon_calendar.gif"></a></span>
          
          
      </div>
      
      </div>
  
</fieldset>

  
  <input name="animatorassignedvillage_set-1-id" id="id_animatorassignedvillage_set-1-id" type="hidden">
  <input name="animatorassignedvillage_set-1-animator" id="id_animatorassignedvillage_set-1-animator" type="hidden">
</div>

<div class="inline-related last-related">
  <h3><b>Animator Assigned Village:</b>&nbsp; #3
    
  </h3>
  
  

  
    <fieldset class="module aligned ">
  
  
  
      <div class="form-row village  ">
      
      
      <div>
          
              <label for="id_animatorassignedvillage_set-2-village" class="required">Village:</label><select name="animatorassignedvillage_set-2-village" id="id_animatorassignedvillage_set-2-village">
<option value="" selected="selected">---------</option>
<option value="19">village1</option>
</select><a href="http://174.129.13.106:8000/admin/dashboard/village/add/" class="add-another" id="add_id_animatorassignedvillage_set-2-village" onclick="return showAddAnotherPopup(this);"> <img src="add_animator_files/icon_addlink.gif" alt="Add Another" height="10" width="10"></a>
          
          
      </div>
      
      </div>
  
      <div class="form-row start_date  ">
      
      
      <div>
          
              <label for="id_animatorassignedvillage_set-2-start_date">Start date:</label><input id="id_animatorassignedvillage_set-2-start_date" class="vDateField" name="animatorassignedvillage_set-2-start_date" size="10" type="text"><span>&nbsp;<a href="javascript:DateTimeShortcuts.handleCalendarQuickLink(2,%200);">Today</a>&nbsp;|&nbsp;<a id="calendarlink2" href="javascript:DateTimeShortcuts.openCalendar(2);"><img alt="Calendar" src="add_animator_files/icon_calendar.gif"></a></span>
          
          
      </div>
      
      </div>
  
</fieldset>

  
  <input name="animatorassignedvillage_set-2-id" id="id_animatorassignedvillage_set-2-id" type="hidden">
  <input name="animatorassignedvillage_set-2-animator" id="id_animatorassignedvillage_set-2-animator" type="hidden">
</div-->





</div>






<div class="submit-row">
<input value="Save" class="default" name="_save" type="submit">
</div>



   <script type="text/javascript">document.getElementById("id_name").focus();</script>



<script type="text/javascript">

</script>


</div>
</form></div>

        
        <br class="clear">
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

dg/templates/add_language.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml:lang="en-us" xmlns="http://www.w3.org/1999/xhtml" lang="en-us"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">


<title>Add language | Django site admin</title>
<link rel="stylesheet" type="text/css" href="/media/css/base.css">
<link rel="stylesheet" type="text/css" href="/media/css/forms.css">
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/media/css/ie.css" /><![endif]-->


<script type="text/javascript" src="/media/js/a"></script>
<script type="text/javascript" src="/media/js/core.js"></script>
<script type="text/javascript" src="/media/js/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/media/js/getElementsBySelector.js"></script>
<script type="text/javascript" src="/media/js/actions.js"></script>

<meta name="robots" content="NONE,NOARCHIVE">
</head><body class="dashboard-language change-form">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name">Digital Green administration</h1>

        </div>
        
        <div id="user-tools">
            Welcome,
            <strong>digitalgreen</strong>.
            
                
                
                    <a href="/admin/doc/">Documentation</a> /
                
                
                
                    <a href="/admin/password_change/">
                
                Change password</a> /
                
                
                    <a href="/admin/logout/">
                
                Log out</a>
            
        </div>
        
        
    </div>
    <!-- END Header -->
    
<div class="breadcrumbs">
     <a href="/admin/">Home</a> ›
     <a href="/admin/dashboard/">Dashboard</a> › 
     <a href="/admin/dashboard/language/">Languages</a> › 
     Add language
</div>

    

        

    <!-- Content -->
    <div id="content" class="colM">
        
        <h1>Add language</h1>
        <div id="content-main">



<form enctype="multipart/form-data" action="" method="post" id="language_form">
<div>





  <fieldset class="module aligned ">
  
  
  
      <div class="form-row language_name  ">
      
      
      <div>
          
              <label for="id_language_name" class="required">Language name:</label><input id="id_language_name" class="vTextField" name="language_name" maxlength="100" type="text">
          
          
      </div>
      
      </div>
  
</fieldset>










<div class="submit-row">
<input value="Save" class="default" name="_save" type="submit">


<input value="Save and add another" name="_addanother" type="submit">
<input value="Save and continue editing" name="_continue" type="submit">
</div>



   <script type="text/javascript">document.getElementById("id_language_name").focus();</script>



<script type="text/javascript">

</script>


</div>
</form></div>

        
        <br class="clear">
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body></html>